language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet karma
  - server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=PhantomJS
#  - karma start karma-e2e.conf.js --reporters=dots --browsers=PhantomJS
